mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logging:
  level:
    org.victor.stackora.mapper: DEBUG

server:
  servlet:
    context-path: /api
    session:
      timeout: 5m
      cookie:
        http-only: true
        same-site: lax
        secure: false
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: org.victor.stackora.controller

